//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf, Subject } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { environment } from 'src/environments/environment';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class AuthorizationController {



    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : environment.DomainAuthURL;
    }

    /**
        * @return Success
        */
    getAllFunctions(): Observable<UaFunctionIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/GetAllFunctions";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetAllFunctions(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAllFunctions(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<UaFunctionIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<UaFunctionIEnumerableCommonResponse>;
        }));
    }

    protected processGetAllFunctions(response: HttpResponseBase): Observable<UaFunctionIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as UaFunctionIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return Success
     */
    getRoleHierarchy(): Observable<RoleHierarchyIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/GetRoleHierarchy";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetRoleHierarchy(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetRoleHierarchy(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<RoleHierarchyIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<RoleHierarchyIEnumerableCommonResponse>;
        }));
    }

    protected processGetRoleHierarchy(response: HttpResponseBase): Observable<RoleHierarchyIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as RoleHierarchyIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return Success
     */
    getSideBarMenu(): Observable<SwbPrivilegeIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/GetSideBarMenu";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetSideBarMenu(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetSideBarMenu(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SwbPrivilegeIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SwbPrivilegeIEnumerableCommonResponse>;
        }));
    }

    protected processGetSideBarMenu(response: HttpResponseBase): Observable<SwbPrivilegeIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SwbPrivilegeIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param updateStateMent (optional) 
     * @param roleId (optional) 
     * @return Success
     */
    updateStatement(updateStateMent: string | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/UpdateStatement?";
        if (updateStateMent === null)
            throw new Error("The parameter 'updateStateMent' cannot be null.");
        else if (updateStateMent !== undefined)
            url_ += "UpdateStateMent=" + encodeURIComponent("" + updateStateMent) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processUpdateStatement(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateStatement(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processUpdateStatement(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
    /**
     * @param roleId (optional) 
     * @param body (optional) 
     * @return Success
     */
    insertFunctionNewToRole(roleId: string | undefined, body: UaFunction | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/InsertFunctionNewToRole?";
        if (roleId === null)
            throw new Error("The parameter 'roleId' cannot be null.");
        else if (roleId !== undefined)
            url_ += "RoleId=" + encodeURIComponent("" + roleId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processInsertFunctionNewToRole(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processInsertFunctionNewToRole(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processInsertFunctionNewToRole(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param functionId (optional) 
     * @return Success
     */
    removeFunction(functionId: string | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/RemoveFunction?";
        if (functionId === null)
            throw new Error("The parameter 'functionId' cannot be null.");
        else if (functionId !== undefined)
            url_ += "FunctionId=" + encodeURIComponent("" + functionId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processRemoveFunction(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRemoveFunction(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processRemoveFunction(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createRole(body: RoleMasterAddDto | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/CreateRole";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processCreateRole(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateRole(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processCreateRole(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    changePassWord(body: ChangePassword | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/ChangePassWord";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processChangePassWord(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processChangePassWord(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processChangePassWord(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param userid (optional) 
     * @return Success
     */
    resetPassword(userid: string | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/ResetPassword?";
        if (userid === null)
            throw new Error("The parameter 'userid' cannot be null.");
        else if (userid !== undefined)
            url_ += "userid=" + encodeURIComponent("" + userid) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processResetPassword(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processResetPassword(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processResetPassword(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return Success
     */
    getEnpoStructure(): Observable<EnpoTeamStructureIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/GetEnpoStructure";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetEnpoStructure(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetEnpoStructure(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<EnpoTeamStructureIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<EnpoTeamStructureIEnumerableCommonResponse>;
        }));
    }

    protected processGetEnpoStructure(response: HttpResponseBase): Observable<EnpoTeamStructureIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as EnpoTeamStructureIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return Success
     */
    getUsersTreeObject(): Observable<VwUserTeamRegistrationIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/Authorization/GetUsersTreeObject";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetUsersTreeObject(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetUsersTreeObject(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<VwUserTeamRegistrationIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<VwUserTeamRegistrationIEnumerableCommonResponse>;
        }));
    }

    protected processGetUsersTreeObject(response: HttpResponseBase): Observable<VwUserTeamRegistrationIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as VwUserTeamRegistrationIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export interface SwbPrivilegeIEnumerableCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: SwbPrivilege[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}
export interface RoleHierarchy {
    roleId: string | undefined;
    roleNameEn: string | undefined;
    roleNameAr: string | undefined;
    applicationId: string | undefined;
    isGlobal: boolean | undefined;
    functionIntId: number;
    functionId: string | undefined;
    functionName: string | undefined;
}

export interface RoleHierarchyIEnumerableCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: RoleHierarchy[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}
export interface EnpoTeamStructure {
    id: number;
    nameAr: string | undefined;
    parentId: number | undefined;
    isSinglePosition: boolean | undefined;
}

export interface EnpoTeamStructureIEnumerableCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: EnpoTeamStructure[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}


export interface AuthorizationNew {
    department: string | undefined;
    firstName: string | undefined;
    userName: string | undefined;
    token: string | undefined;
    functions: string | undefined;
    exchangeUserInfo: ExchangeUserInfo;
    privilageCollection: SwbPrivilege[] | undefined;
}

export interface AuthorizationNewCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: AuthorizationNew;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}

export interface BooleanCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: boolean;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}

export interface DomainRegistrationRequest {
    id: number;
    regUserId: string | undefined;
    regName: string | undefined;
    regCat: number | undefined;
    regRealName: string | undefined;
    regTitle: string | undefined;
    regGender: string | undefined;
    regGsm: string | undefined;
    regEmail: string | undefined;
    regDate: Date | undefined;
    regAproved: number;
    regAprrovedby: string | undefined;
    regIp: string | undefined;
    regApplicationId: string | undefined;
}

export interface DomainRegistrationRequestListCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: DomainRegistrationRequest[] | undefined;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}

export interface ErrorDto {
    code: string | undefined;
    message: string | undefined;
}

export interface ExchangeUserInfo {
    userEmail: string | undefined;
    userDisplayName: string | undefined;
    userTitle: string | undefined;
    mobilePhone: string | undefined;
    userPicture: string | undefined;
    registrationStatus: boolean | undefined;
    userId: string | undefined;
    isGroup: boolean;
    groupMembers: ExchangeUserInfo[] | undefined;
    userGroups: string[] | undefined;
    userOtpEnrollmentDto?: UserOtpEnrollmentDto | null;
}

export interface UserOtpEnrollmentDto {
    id: number;
    userId: string;
    issuer: string;
    isActive: boolean;
}

export interface ExchangeUserInfoCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: ExchangeUserInfo;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}

export interface RoleMasterAddDto {
    roleId: string | undefined;
    roleNameEn: string | undefined;
    roleNameAr: string | undefined;
    applicationId: string | undefined;
}

export interface StringCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: string | undefined;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}

export interface SwbPrivilege {
    sbId: number;
    sbSubId: number | undefined;
    itemName: string | undefined;
    sbRoute: string | undefined;
    sbStatus: boolean;
    sbType: string;
    functionIntId: number | undefined;
    functionName: string | undefined;
    roleId: string | undefined;
    roleNameAr: string | undefined;
    sbApplicationId: string | undefined;
}

export interface UaFunction {
    functionIntId: number;
    menuIntId: number;
    functionId: string | undefined;
    functionName: string | undefined;
    objectId: string | undefined;
    statusId: string | undefined;
    createdBy: string | undefined;
    createdDate: Date | undefined;
    modifiedBy: string | undefined;
    modifiedDate: Date | undefined;
    modifiedOsUser: string | undefined;
    modifiedTerminal: string | undefined;
    sbApplication_Id: string | undefined;
    uaRolePrivileges: UaRolePrivilege[] | undefined;
}

export interface UaFunctionIEnumerableCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: UaFunction[] ;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}

export interface UaRoleMaster {
    roleId: string | undefined;
    roleNameEn: string | undefined;
    roleNameAr: string | undefined;
    statusId: string | undefined;
    createdBy: string | undefined;
    createdDate: Date | undefined;
    modifiedBy: string | undefined;
    modifiedDate: Date | undefined;
    modifiedOsUser: string | undefined;
    modifiedTerminal: string | undefined;
    applicationId: string | undefined;
    isGlobal: boolean | undefined;
    uaRolePrivileges: UaRolePrivilege[] | undefined;
    uaUserRolePrivileges: UaUserRolePrivilege[] | undefined;
}

export interface UaRolePrivilege {
    roleId: string | undefined;
    functionIntId: number;
    beginDate: Date | undefined;
    endDate: Date | undefined;
    statusId: string | undefined;
    createdBy: string | undefined;
    createdDate: Date | undefined;
    modifiedBy: string | undefined;
    modifiedDate: Date | undefined;
    modifiedOsUser: string | undefined;
    modifiedTerminal: string | undefined;
    functionInt: UaFunction;
    role: UaRoleMaster;
}

export interface UaUserRolePrivilege {
    userId: string | undefined;
    roleId: string | undefined;
    officeSectionIntId: number;
    beginDate: Date;
    endDate: Date | undefined;
    statusId: string | undefined;
    createdBy: string | undefined;
    createdDate: Date | undefined;
    modifiedBy: string | undefined;
    modifiedDate: Date | undefined;
    modifiedOsUser: string | undefined;
    modifiedTerminal: string | undefined;
}

export interface VwUserTeamRegistration {
    userUserId: string | undefined;
    effectiveDateFrom: Date | undefined;
    effectiveDateTo: Date | undefined;
    status: number | undefined;
    createdOn: Date | undefined;
    createdBy: string | undefined;
    lastUpdated: Date | undefined;
    lastUpdatedBy: string | undefined;
    resetPassword: boolean | undefined;
    lastPasswordDate: Date | undefined;
    nextPasswordDate: Date | undefined;
    loginStatus: string | undefined;
    nationalId: number | undefined;
    arabicName: string;
    englishName: string | undefined;
    mobileNumber: string | undefined;
    emailAddress: string | undefined;
    regId: number | undefined;
    regUserId: string | undefined;
    regName: string | undefined;
    regCat: number;
    regRealName: string | undefined;
    regTitle: string | undefined;
    regGender: string | undefined;
    regGsm: string | undefined;
    regEmail: string | undefined;
    regDate: Date | undefined;
    regAproved: boolean | undefined;
    regAprrovedby: string | undefined;
    regIp: string | undefined;
    applicationId: string | undefined;
    applicationNameAr: string | undefined;
    tittlId: number | undefined;
    userTeamTittle: string | undefined;
    parentId: number;
    isSinglePosition: boolean | undefined;
    managerId: number | undefined;
    managerName: string | undefined;
}

export interface VwUserTeamRegistrationIEnumerableCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: VwUserTeamRegistration[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}

export interface ChangePassword {
    oldPassword: string;
    newPassword: string;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}