//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { SafeUrl } from '@angular/platform-browser';
import { environment } from 'src/environments/environment';
import { UserOtpEnrollmentDto } from 'src/app/shared/services/helper/auth-objects.service';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class SSOController {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : environment.SSoURL;
    }

    /**
     * @return Success
     */
    authanticateMe(): Observable<ExchangeUserInfoCommonResponse> {
        let url_ = this.baseUrl + "/api/DomainAuthorization/AuthanticateMe";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processAuthanticateMe(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAuthanticateMe(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ExchangeUserInfoCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ExchangeUserInfoCommonResponse>;
        }));
    }

    protected processAuthanticateMe(response: HttpResponseBase): Observable<ExchangeUserInfoCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ExchangeUserInfoCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status == 0) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("401 Unauthorized error detected", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param username (optional) 
     * @param password (optional) 
     * @return Success
     */
    authenticateDomainUser(username: string | undefined, password: string | undefined): Observable<BooleanCommonResponse> {
        let url_ = this.baseUrl + "/api/DomainAuthorization/AuthenticateDomainUser?";
        if (username === null)
            throw new Error("The parameter 'username' cannot be null.");
        else if (username !== undefined)
            url_ += "username=" + encodeURIComponent("" + username) + "&";
        if (password === null)
            throw new Error("The parameter 'password' cannot be null.");
        else if (password !== undefined)
            url_ += "password=" + encodeURIComponent("" + password) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processAuthenticateDomainUser(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAuthenticateDomainUser(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<BooleanCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<BooleanCommonResponse>;
        }));
    }

    protected processAuthenticateDomainUser(response: HttpResponseBase): Observable<BooleanCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BooleanCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param username (optional) 
     * @param password (optional) 
     * @return Success
     */
    getUserDetails(username: string | undefined, password: string | undefined): Observable<ExchangeUserInfoCommonResponse> {
        let url_ = this.baseUrl + "/api/DomainAuthorization/GetUserDetails?";
        if (username === null)
            throw new Error("The parameter 'username' cannot be null.");
        else if (username !== undefined)
            url_ += "username=" + encodeURIComponent("" + username) + "&";
        if (password === null)
            throw new Error("The parameter 'password' cannot be null.");
        else if (password !== undefined)
            url_ += "password=" + encodeURIComponent("" + password) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetUserDetails(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetUserDetails(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ExchangeUserInfoCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ExchangeUserInfoCommonResponse>;
        }));
    }

    protected processGetUserDetails(response: HttpResponseBase): Observable<ExchangeUserInfoCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ExchangeUserInfoCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param targetEmail (optional) 
     * @return Success
     */
    isEmailExistInExchange(targetEmail: string | undefined): Observable<ExchangeUserInfoCommonResponse> {
        let url_ = this.baseUrl + "/api/DomainAuthorization/IsEmailExistInExchange?";
        if (targetEmail === null)
            throw new Error("The parameter 'targetEmail' cannot be null.");
        else if (targetEmail !== undefined)
            url_ += "targetEmail=" + encodeURIComponent("" + targetEmail) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processIsEmailExistInExchange(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processIsEmailExistInExchange(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ExchangeUserInfoCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ExchangeUserInfoCommonResponse>;
        }));
    }

    protected processIsEmailExistInExchange(response: HttpResponseBase): Observable<ExchangeUserInfoCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ExchangeUserInfoCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param targetEmail (optional) 
     * @return Success
     */
    searchDomainName(targetEmail: string | undefined): Observable<ExchangeUserInfoListCommonResponse> {
        let url_ = this.baseUrl + "/api/DomainAuthorization/SearchDomainName?";
        if (targetEmail === null)
            throw new Error("The parameter 'targetEmail' cannot be null.");
        else if (targetEmail !== undefined)
            url_ += "targetEmail=" + encodeURIComponent("" + targetEmail) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processSearchDomainName(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearchDomainName(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ExchangeUserInfoListCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ExchangeUserInfoListCommonResponse>;
        }));
    }

    protected processSearchDomainName(response: HttpResponseBase): Observable<ExchangeUserInfoListCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ExchangeUserInfoListCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param identityName (optional) 
     * @param applicationId (optional) 
     * @return Success
     */
    authorizeWithOutPassword(identityName: string | undefined, applicationId: string | undefined): Observable<AuthorizationNewCommonResponse> {
        let url_ = this.baseUrl + "/api/DomainAuthorization/AuthorizeWithOutPassword?";
        if (identityName === null)
            throw new Error("The parameter 'identityName' cannot be null.");
        else if (identityName !== undefined)
            url_ += "IdentityName=" + encodeURIComponent("" + identityName) + "&";
        if (applicationId === null)
            throw new Error("The parameter 'applicationId' cannot be null.");
        else if (applicationId !== undefined) {
            url_ += "applicationId=" + encodeURIComponent("" + applicationId) + "&";
            url_ += "ristrationIsrequired=" + encodeURIComponent("" + true);
        }
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processAuthorizeWithOutPassword(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAuthorizeWithOutPassword(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<AuthorizationNewCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<AuthorizationNewCommonResponse>;
        }));
    }

    protected processAuthorizeWithOutPassword(response: HttpResponseBase): Observable<AuthorizationNewCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AuthorizationNewCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param applicationId (optional) 
     * @param body (optional) 
     * @return Success
     */
    authorizeWithPassword(applicationId: string | undefined, body: LoginModel | undefined): Observable<AuthorizationNewCommonResponse> {
        let url_ = this.baseUrl + "/api/DomainAuthorization/AuthorizeWithPassword?";
        if (applicationId === null)
            throw new Error("The parameter 'applicationId' cannot be null.");
        else if (applicationId !== undefined)
            url_ += "applicationId=" + encodeURIComponent("" + applicationId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processAuthorizeWithPassword(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAuthorizeWithPassword(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<AuthorizationNewCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<AuthorizationNewCommonResponse>;
        }));
    }

    protected processAuthorizeWithPassword(response: HttpResponseBase): Observable<AuthorizationNewCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AuthorizationNewCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
    /**
    * @param userId (optional) 
    * @param applicationId (optional) 
    * @return Success
    */
    registerMe(userId: string | undefined, applicationId: string | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/Registeration/RegisterMe?";
        if (userId === null)
            throw new Error("The parameter 'userId' cannot be null.");
        else if (userId !== undefined)
            url_ += "userId=" + encodeURIComponent("" + userId) + "&";
        if (applicationId === null)
            throw new Error("The parameter 'applicationId' cannot be null.");
        else if (applicationId !== undefined)
            url_ += "applicationId=" + encodeURIComponent("" + applicationId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processRegisterMe(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRegisterMe(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processRegisterMe(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param userId (optional) 
     * @param user (optional) 
     * @param applicationId (optional) 
     * @return Success
     */
    registerUser(userId: string | undefined, user: string | undefined, applicationId: string | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/Registeration/RegisterUser?";
        if (userId === null)
            throw new Error("The parameter 'userId' cannot be null.");
        else if (userId !== undefined)
            url_ += "userId=" + encodeURIComponent("" + userId) + "&";
        if (user === null)
            throw new Error("The parameter 'user' cannot be null.");
        else if (user !== undefined)
            url_ += "user=" + encodeURIComponent("" + user) + "&";
        if (applicationId === null)
            throw new Error("The parameter 'applicationId' cannot be null.");
        else if (applicationId !== undefined)
            url_ += "applicationId=" + encodeURIComponent("" + applicationId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processRegisterUser(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRegisterUser(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processRegisterUser(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    registerApproval(body: DomainRegistrationRequest | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/Registeration/RegisterApproval";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processRegisterApproval(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRegisterApproval(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processRegisterApproval(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }


    /**
     * @param pageNumber (optional) 
     * @param pageSize (optional) 
     * @return Success
     */
    getAllRegistrationRequests(pageNumber: number | undefined, pageSize: number | undefined): Observable<DomainRegistrationRequestListCommonResponse> {
        let url_ = this.baseUrl + "/api/Registeration/GetAllRegistrationRequests?";
        if (pageNumber === null)
            throw new Error("The parameter 'pageNumber' cannot be null.");
        else if (pageNumber !== undefined)
            url_ += "pageNumber=" + encodeURIComponent("" + pageNumber) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetAllRegistrationRequests(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAllRegistrationRequests(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DomainRegistrationRequestListCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DomainRegistrationRequestListCommonResponse>;
        }));
    }

    protected processGetAllRegistrationRequests(response: HttpResponseBase): Observable<DomainRegistrationRequestListCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as DomainRegistrationRequestListCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export interface DomainRegistrationRequest {
    id: number;
    regUserId: string | undefined;
    regName: string | undefined;
    regCat: number | undefined;
    regRealName: string | undefined;
    regTitle: string | undefined;
    regGender: string | undefined;
    regGsm: string | undefined;
    regEmail: string | undefined;
    regDate: Date | undefined;
    regAproved: number;
    regAprrovedby: string | undefined;
    regIp: string | undefined;
    regApplicationId: string | undefined;
}

export interface DomainRegistrationRequestListCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: DomainRegistrationRequest[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}
export interface LoginModel {
    userId: string;
    password: string;
}

export interface SwbPrivilege {
    sbId: number;
    sbSubId: number | undefined;
    itemName: string | undefined;
    sbRoute: string | undefined;
    sbStatus: boolean;
    sbType: string | undefined;
    functionIntId: number | undefined;
    functionName: string | undefined;
    roleId: string | undefined;
    roleNameAr: string | undefined;
    applicationId: string | undefined;
}
export interface AuthorizationNew {
    department: string | undefined;
    firstName: string | undefined;
    userName: string | undefined;
    token: string | undefined;
    functions: string | undefined;
    exchangeUserInfo: ExchangeUserInfo;
    userOtpEnrollmentDto?: UserOtpEnrollmentDto | null;
    privilageCollection: SwbPrivilege[] | undefined;
}

export interface AuthorizationNewCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: AuthorizationNew;
}
export interface BooleanCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: boolean;
}

export interface ErrorDto {
    code: string | undefined;
    message: string | undefined;
}


export interface ExchangeUserInfo {
    userEmail: string | undefined;
    userDisplayName: string | undefined;
    userTitle: string | undefined;
    mobilePhone: string | undefined;
    userPicture: string | undefined;
    safeImage: SafeUrl;
    registrationStatus: boolean | undefined;
    userId: string | undefined;
    isGroup: boolean;
    groupMembers: ExchangeUserInfo[] | undefined;
    userGroups: string[] | undefined;
}

export interface ExchangeUserInfoCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: ExchangeUserInfo;
}

export interface ExchangeUserInfoListCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: ExchangeUserInfo[] | undefined;
}

export interface StringCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}