import { environment } from 'src/environments/environment';
import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { FileParameter, ErrorDto, API_BASE_URL, throwException, blobToText } from '../dto-shared';
import { ExpressionDto, DocumentRespPagedResult, ObjectResponse, AttachmentList, SaveDocumentResp, FileContentResp, EditActiveRequestDto, AttachmentStatusDto, SaveAttachmentResp, AttachmentDto, DistrictsResp, DistrictRequestDto, SaveDistrictResp, PublicationTypeResp, PublicationTypeRequestDto, SavePublicationTypeResp, Menu_ItemResp, MenuItemReq, MenuItemResp, ResponseDetail, DocumentResp, District, PublicationType, PUB_MENU_ITEMS, DocumentType, Sector, Document, Category, MainService, ServiceType, SubService, DOC_ATTACHMENT } from './Publications.dto';

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming@Injectable({ providedIn: "root" })
export class PublicationsController {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : environment.PublicationsUrl;
    }

    /**
     * @param pageNumber (optional) 
     * @param pageSize (optional) 
     * @param body (optional) 
     * @return Success
     */
    getDocumentsList_admin(pageNumber: number | undefined, pageSize: number | undefined, body: ExpressionDto[] | undefined): Observable<DocumentRespPagedResult> {
        let url_ = this.baseUrl + "/api/Publications/GetDocumentsList_admin?";
        if (pageNumber === null)
            throw new Error("The parameter 'pageNumber' cannot be null.");
        else if (pageNumber !== undefined)
            url_ += "pageNumber=" + encodeURIComponent("" + pageNumber) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetDocumentsList_admin(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetDocumentsList_admin(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DocumentRespPagedResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DocumentRespPagedResult>;
        }));
    }

    protected processGetDocumentsList_admin(response: HttpResponseBase): Observable<DocumentRespPagedResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as DocumentRespPagedResult;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param pageNumber (optional) 
     * @param pageSize (optional) 
     * @param body (optional) 
     * @return Success
     */
    getDocumentsList_user(pageNumber: number | undefined, pageSize: number | undefined, body: ExpressionDto[] | undefined): Observable<DocumentRespPagedResult> {
        let url_ = this.baseUrl + "/api/Publications/GetDocumentsList_user?";
        if (pageNumber === null)
            throw new Error("The parameter 'pageNumber' cannot be null.");
        else if (pageNumber !== undefined)
            url_ += "pageNumber=" + encodeURIComponent("" + pageNumber) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetDocumentsList_user(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetDocumentsList_user(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DocumentRespPagedResult>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DocumentRespPagedResult>;
        }));
    }

    protected processGetDocumentsList_user(response: HttpResponseBase): Observable<DocumentRespPagedResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as DocumentRespPagedResult;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param funName (optional) 
     * @return Success
     */
    getCriteria(funName: string | undefined): Observable<ObjectResponse> {
        let url_ = this.baseUrl + "/api/Publications/GetCriteria?";
        if (funName === null)
            throw new Error("The parameter 'funName' cannot be null.");
        else if (funName !== undefined)
            url_ += "funName=" + encodeURIComponent("" + funName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCriteria(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCriteria(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ObjectResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ObjectResponse>;
        }));
    }

    protected processGetCriteria(response: HttpResponseBase): Observable<ObjectResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ObjectResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param dOCUMENT_ID (optional) 
     * @param wORKING_START_DATE (optional) 
     * @param mINI_DOC (optional) 
     * @param dISTRICT_ID (optional) 
     * @param pUBLICATION_TYPE_ID (optional) 
     * @param aLL_TEXT_DOC (optional) 
     * @param mENUITEMID (optional) 
     * @param dOCUMENT_PARENT_ID (optional) 
     * @param rEJECTREASON (optional) 
     * @param attachmentLists (optional) 
     * @param files (optional) 
     * @return Success
     */
    saveDocument(dOCUMENT_ID: number | undefined, wORKING_START_DATE: Date | undefined, mINI_DOC: string | undefined, dISTRICT_ID: number | undefined, pUBLICATION_TYPE_ID: number | undefined, aLL_TEXT_DOC: string | undefined, mENUITEMID: number | undefined, dOCUMENT_PARENT_ID: string | undefined, rEJECTREASON: string | undefined, attachmentLists: AttachmentList[] | undefined, files: FileParameter[] | undefined): Observable<SaveDocumentResp> {
        let url_ = this.baseUrl + "/api/Publications/SaveDocument";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (dOCUMENT_ID === null || dOCUMENT_ID === undefined)
            throw new Error("The parameter 'dOCUMENT_ID' cannot be null.");
        else
            content_.append("DOCUMENT_ID", dOCUMENT_ID.toString());
        if (wORKING_START_DATE === null || wORKING_START_DATE === undefined)
            throw new Error("The parameter 'wORKING_START_DATE' cannot be null.");
        else
            content_.append("WORKING_START_DATE", wORKING_START_DATE.toJSON());
        if (mINI_DOC === null || mINI_DOC === undefined)
            throw new Error("The parameter 'mINI_DOC' cannot be null.");
        else
            content_.append("MINI_DOC", mINI_DOC.toString());
        if (dISTRICT_ID === null || dISTRICT_ID === undefined)
            throw new Error("The parameter 'dISTRICT_ID' cannot be null.");
        else
            content_.append("DISTRICT_ID", dISTRICT_ID.toString());
        if (pUBLICATION_TYPE_ID === null || pUBLICATION_TYPE_ID === undefined)
            throw new Error("The parameter 'pUBLICATION_TYPE_ID' cannot be null.");
        else
            content_.append("PUBLICATION_TYPE_ID", pUBLICATION_TYPE_ID.toString());
        if (aLL_TEXT_DOC === null || aLL_TEXT_DOC === undefined)
            throw new Error("The parameter 'aLL_TEXT_DOC' cannot be null.");
        else
            content_.append("ALL_TEXT_DOC", aLL_TEXT_DOC.toString());
        if (mENUITEMID === null || mENUITEMID === undefined)
            throw new Error("The parameter 'mENUITEMID' cannot be null.");
        else
            content_.append("MENUITEMID", mENUITEMID.toString());
        if (dOCUMENT_PARENT_ID === null || dOCUMENT_PARENT_ID === undefined)
            throw new Error("The parameter 'dOCUMENT_PARENT_ID' cannot be null.");
        else
            content_.append("DOCUMENT_PARENT_ID", dOCUMENT_PARENT_ID.toString());
        if (rEJECTREASON === null || rEJECTREASON === undefined)
            throw new Error("The parameter 'rEJECTREASON' cannot be null.");
        else
            content_.append("REJECTREASON", rEJECTREASON.toString());
        if (attachmentLists === null || attachmentLists === undefined)
            throw new Error("The parameter 'attachmentLists' cannot be null.");
        else
            attachmentLists.forEach(item_ => content_.append("attachmentLists", item_.toString()));
        if (files === null || files === undefined)
            throw new Error("The parameter 'files' cannot be null.");
        else
            files.forEach(item_ => content_.append("Files", item_.data, item_.fileName ? item_.fileName : "Files") );

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSaveDocument(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSaveDocument(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SaveDocumentResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SaveDocumentResp>;
        }));
    }

    protected processSaveDocument(response: HttpResponseBase): Observable<SaveDocumentResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SaveDocumentResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param attchmentId (optional) 
     * @return Success
     */
    getFileContent(attchmentId: number | undefined): Observable<FileContentResp> {
        let url_ = this.baseUrl + "/api/Publications/GetFileContent?";
        if (attchmentId === null)
            throw new Error("The parameter 'attchmentId' cannot be null.");
        else if (attchmentId !== undefined)
            url_ += "attchmentId=" + encodeURIComponent("" + attchmentId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetFileContent(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetFileContent(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FileContentResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FileContentResp>;
        }));
    }

    protected processGetFileContent(response: HttpResponseBase): Observable<FileContentResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as FileContentResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param dOCUMENT_ID (optional) 
     * @param wORKING_START_DATE (optional) 
     * @param mINI_DOC (optional) 
     * @param dISTRICT_ID (optional) 
     * @param pUBLICATION_TYPE_ID (optional) 
     * @param aLL_TEXT_DOC (optional) 
     * @param mENUITEMID (optional) 
     * @param dOCUMENT_PARENT_ID (optional) 
     * @param rEJECTREASON (optional) 
     * @param attachmentLists (optional) 
     * @param files (optional) 
     * @return Success
     */
    editDocument(dOCUMENT_ID: number | undefined, wORKING_START_DATE: Date | undefined, mINI_DOC: string | undefined, dISTRICT_ID: number | undefined, pUBLICATION_TYPE_ID: number | undefined, aLL_TEXT_DOC: string | undefined, mENUITEMID: number | undefined, dOCUMENT_PARENT_ID: string | undefined, rEJECTREASON: string | undefined, attachmentLists: AttachmentList[] | undefined, files: FileParameter[] | undefined): Observable<SaveDocumentResp> {
        let url_ = this.baseUrl + "/api/Publications/EditDocument";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (dOCUMENT_ID === null || dOCUMENT_ID === undefined)
            throw new Error("The parameter 'dOCUMENT_ID' cannot be null.");
        else
            content_.append("DOCUMENT_ID", dOCUMENT_ID.toString());
        if (wORKING_START_DATE === null || wORKING_START_DATE === undefined)
            throw new Error("The parameter 'wORKING_START_DATE' cannot be null.");
        else
            content_.append("WORKING_START_DATE", wORKING_START_DATE.toJSON());
        if (mINI_DOC === null || mINI_DOC === undefined)
            throw new Error("The parameter 'mINI_DOC' cannot be null.");
        else
            content_.append("MINI_DOC", mINI_DOC.toString());
        if (dISTRICT_ID === null || dISTRICT_ID === undefined)
            throw new Error("The parameter 'dISTRICT_ID' cannot be null.");
        else
            content_.append("DISTRICT_ID", dISTRICT_ID.toString());
        if (pUBLICATION_TYPE_ID === null || pUBLICATION_TYPE_ID === undefined)
            throw new Error("The parameter 'pUBLICATION_TYPE_ID' cannot be null.");
        else
            content_.append("PUBLICATION_TYPE_ID", pUBLICATION_TYPE_ID.toString());
        if (aLL_TEXT_DOC === null || aLL_TEXT_DOC === undefined)
            throw new Error("The parameter 'aLL_TEXT_DOC' cannot be null.");
        else
            content_.append("ALL_TEXT_DOC", aLL_TEXT_DOC.toString());
        if (mENUITEMID === null || mENUITEMID === undefined)
            throw new Error("The parameter 'mENUITEMID' cannot be null.");
        else
            content_.append("MENUITEMID", mENUITEMID.toString());
        if (dOCUMENT_PARENT_ID === null || dOCUMENT_PARENT_ID === undefined)
            throw new Error("The parameter 'dOCUMENT_PARENT_ID' cannot be null.");
        else
            content_.append("DOCUMENT_PARENT_ID", dOCUMENT_PARENT_ID.toString());
        if (rEJECTREASON === null || rEJECTREASON === undefined)
            throw new Error("The parameter 'rEJECTREASON' cannot be null.");
        else
            content_.append("REJECTREASON", rEJECTREASON.toString());
        if (attachmentLists === null || attachmentLists === undefined)
            throw new Error("The parameter 'attachmentLists' cannot be null.");
        else
            attachmentLists.forEach(item_ => content_.append("attachmentLists", item_.toString()));
        if (files === null || files === undefined)
            throw new Error("The parameter 'files' cannot be null.");
        else
            files.forEach(item_ => content_.append("Files", item_.data, item_.fileName ? item_.fileName : "Files") );

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processEditDocument(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processEditDocument(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SaveDocumentResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SaveDocumentResp>;
        }));
    }

    protected processEditDocument(response: HttpResponseBase): Observable<SaveDocumentResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SaveDocumentResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    editActivation(body: EditActiveRequestDto | undefined): Observable<SaveDocumentResp> {
        let url_ = this.baseUrl + "/api/Publications/EditActivation";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processEditActivation(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processEditActivation(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SaveDocumentResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SaveDocumentResp>;
        }));
    }

    protected processEditActivation(response: HttpResponseBase): Observable<SaveDocumentResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SaveDocumentResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    updateAttachmentStatus(body: AttachmentStatusDto | undefined): Observable<SaveAttachmentResp> {
        let url_ = this.baseUrl + "/api/Publications/UpdateAttachmentStatus";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateAttachmentStatus(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateAttachmentStatus(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SaveAttachmentResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SaveAttachmentResp>;
        }));
    }

    protected processUpdateAttachmentStatus(response: HttpResponseBase): Observable<SaveAttachmentResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SaveAttachmentResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    uploadAttachmentPDF(body: AttachmentDto | undefined): Observable<SaveAttachmentResp> {
        let url_ = this.baseUrl + "/api/Publications/UploadAttachmentPDF";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUploadAttachmentPDF(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUploadAttachmentPDF(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SaveAttachmentResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SaveAttachmentResp>;
        }));
    }

    protected processUploadAttachmentPDF(response: HttpResponseBase): Observable<SaveAttachmentResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SaveAttachmentResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param pageNumber (optional) 
     * @param pageSize (optional) 
     * @return Success
     */
    getDistrictsList(pageNumber: number | undefined, pageSize: number | undefined): Observable<DistrictsResp> {
        let url_ = this.baseUrl + "/api/Publications/GetDistrictsList?";
        if (pageNumber === null)
            throw new Error("The parameter 'pageNumber' cannot be null.");
        else if (pageNumber !== undefined)
            url_ += "pageNumber=" + encodeURIComponent("" + pageNumber) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetDistrictsList(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetDistrictsList(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DistrictsResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DistrictsResp>;
        }));
    }

    protected processGetDistrictsList(response: HttpResponseBase): Observable<DistrictsResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as DistrictsResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    saveDistrict(body: DistrictRequestDto | undefined): Observable<SaveDistrictResp> {
        let url_ = this.baseUrl + "/api/Publications/SaveDistrict";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSaveDistrict(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSaveDistrict(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SaveDistrictResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SaveDistrictResp>;
        }));
    }

    protected processSaveDistrict(response: HttpResponseBase): Observable<SaveDistrictResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SaveDistrictResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param pageNumber (optional) 
     * @param pageSize (optional) 
     * @return Success
     */
    getPublicationTypeList(pageNumber: number | undefined, pageSize: number | undefined): Observable<PublicationTypeResp> {
        let url_ = this.baseUrl + "/api/Publications/GetPublicationTypeList?";
        if (pageNumber === null)
            throw new Error("The parameter 'pageNumber' cannot be null.");
        else if (pageNumber !== undefined)
            url_ += "pageNumber=" + encodeURIComponent("" + pageNumber) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPublicationTypeList(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPublicationTypeList(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<PublicationTypeResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<PublicationTypeResp>;
        }));
    }

    protected processGetPublicationTypeList(response: HttpResponseBase): Observable<PublicationTypeResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PublicationTypeResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    savePublicationType(body: PublicationTypeRequestDto | undefined): Observable<SavePublicationTypeResp> {
        let url_ = this.baseUrl + "/api/Publications/SavePublicationType";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSavePublicationType(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSavePublicationType(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<SavePublicationTypeResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<SavePublicationTypeResp>;
        }));
    }

    protected processSavePublicationType(response: HttpResponseBase): Observable<SavePublicationTypeResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SavePublicationTypeResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @return Success
     */
    getMenuItems(): Observable<Menu_ItemResp> {
        let url_ = this.baseUrl + "/api/Publications/GetMenuItems";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetMenuItems(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMenuItems(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<Menu_ItemResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<Menu_ItemResp>;
        }));
    }

    protected processGetMenuItems(response: HttpResponseBase): Observable<Menu_ItemResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Menu_ItemResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    getAdminMenuItems(body: number[] | undefined): Observable<Menu_ItemResp> {
        let url_ = this.baseUrl + "/api/Publications/GetAdminMenuItems";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAdminMenuItems(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAdminMenuItems(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<Menu_ItemResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<Menu_ItemResp>;
        }));
    }

    protected processGetAdminMenuItems(response: HttpResponseBase): Observable<Menu_ItemResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Menu_ItemResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    addMenuItem(body: MenuItemReq | undefined): Observable<MenuItemResp> {
        let url_ = this.baseUrl + "/api/Publications/AddMenuItem";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processAddMenuItem(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAddMenuItem(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MenuItemResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MenuItemResp>;
        }));
    }

    protected processAddMenuItem(response: HttpResponseBase): Observable<MenuItemResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MenuItemResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param menuItemId (optional) 
     * @return Success
     */
    removeMenuItem(menuItemId: number | undefined): Observable<MenuItemResp> {
        let url_ = this.baseUrl + "/api/Publications/RemoveMenuItem?";
        if (menuItemId === null)
            throw new Error("The parameter 'menuItemId' cannot be null.");
        else if (menuItemId !== undefined)
            url_ += "menuItemId=" + encodeURIComponent("" + menuItemId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processRemoveMenuItem(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processRemoveMenuItem(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MenuItemResp>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MenuItemResp>;
        }));
    }

    protected processRemoveMenuItem(response: HttpResponseBase): Observable<MenuItemResp> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MenuItemResp;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}