import { environment } from 'src/environments/environment';
import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { API_BASE_URL, blobToText, FileParameter, throwException } from './dto-shared';
import { CdmendDtoIEnumerableCommonResponse, CdCategoryMandDtoIEnumerableCommonResponse, CdcategoryDtoIEnumerableCommonResponse, TkmendField, MessageDtoCommonResponse, ListRequestModel, MessageDtoIEnumerableCommonResponse } from './DynamicForm/DynamicForm.dto';

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
@Injectable({ providedIn: "root" })
export class DynamicFormController {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : environment.ConnectApiURL;
    }

    /**
     * @param appId (optional) 
     * @return Success
     */
    getMandatoryMetaDate(appId: string | undefined): Observable<CdmendDtoIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/DynamicForm/GetMandatoryMetaDate?";
        if (appId === null)
            throw new Error("The parameter 'appId' cannot be null.");
        else if (appId !== undefined)
            url_ += "appId=" + encodeURIComponent("" + appId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetMandatoryMetaDate(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMandatoryMetaDate(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CdmendDtoIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CdmendDtoIEnumerableCommonResponse>;
        }));
    }

    protected processGetMandatoryMetaDate(response: HttpResponseBase): Observable<CdmendDtoIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CdmendDtoIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param appId (optional) 
     * @return Success
     */
    getMandatoryAll(appId: string | undefined): Observable<CdCategoryMandDtoIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/DynamicForm/GetMandatoryAll?";
        if (appId === null)
            throw new Error("The parameter 'appId' cannot be null.");
        else if (appId !== undefined)
            url_ += "appId=" + encodeURIComponent("" + appId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetMandatoryAll(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMandatoryAll(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CdCategoryMandDtoIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CdCategoryMandDtoIEnumerableCommonResponse>;
        }));
    }

    protected processGetMandatoryAll(response: HttpResponseBase): Observable<CdCategoryMandDtoIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CdCategoryMandDtoIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param appId (optional) 
     * @return Success
     */
    getAllCategories(appId: string | undefined): Observable<CdcategoryDtoIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/DynamicForm/GetAllCategories?";
        if (appId === null)
            throw new Error("The parameter 'appId' cannot be null.");
        else if (appId !== undefined)
            url_ += "appId=" + encodeURIComponent("" + appId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetAllCategories(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAllCategories(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CdcategoryDtoIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CdcategoryDtoIEnumerableCommonResponse>;
        }));
    }

    protected processGetAllCategories(response: HttpResponseBase): Observable<CdcategoryDtoIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CdcategoryDtoIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param messageId (optional) 
     * @param requestRef (optional) 
     * @param subject (optional) 
     * @param description (optional) 
     * @param createdBy (optional) 
     * @param assignedSectorId (optional) 
     * @param unitId (optional) 
     * @param currentResponsibleSectorId (optional) 
     * @param type (optional) 
     * @param categoryCd (optional) 
     * @param fields (optional) 
     * @param files (optional) 
     * @return Success
     */
    createRequest(messageId: number | undefined, requestRef: string | undefined, subject: string | undefined, description: string | undefined, createdBy: string | undefined, assignedSectorId: string | undefined, unitId: number[] | undefined, currentResponsibleSectorId: string | undefined, type: number | undefined, categoryCd: number | undefined, fields: TkmendField[] | undefined, files: FileParameter[] | undefined): Observable<MessageDtoCommonResponse> {
        let url_ = this.baseUrl + "/api/DynamicForm/CreateRequest";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (messageId === null || messageId === undefined)
            throw new Error("The parameter 'messageId' cannot be null.");
        else
            content_.append("MessageId", messageId.toString());
        if (requestRef === null || requestRef === undefined)
            throw new Error("The parameter 'requestRef' cannot be null.");
        else
            content_.append("RequestRef", requestRef.toString());
        if (subject === null || subject === undefined)
            throw new Error("The parameter 'subject' cannot be null.");
        else
            content_.append("Subject", subject.toString());
        if (description === null || description === undefined)
            throw new Error("The parameter 'description' cannot be null.");
        else
            content_.append("Description", description.toString());
        if (createdBy === null || createdBy === undefined)
            throw new Error("The parameter 'createdBy' cannot be null.");
        else
            content_.append("CreatedBy", createdBy.toString());
        if (assignedSectorId === null || assignedSectorId === undefined)
            throw new Error("The parameter 'assignedSectorId' cannot be null.");
        else
            content_.append("AssignedSectorId", assignedSectorId.toString());
        if (unitId === null || unitId === undefined)
            throw new Error("The parameter 'unitId' cannot be null.");
        else
            unitId.forEach(item_ => content_.append("UnitId", item_.toString()));
        if (currentResponsibleSectorId === null || currentResponsibleSectorId === undefined)
            throw new Error("The parameter 'currentResponsibleSectorId' cannot be null.");
        else
            content_.append("CurrentResponsibleSectorId", currentResponsibleSectorId.toString());
        if (type === null || type === undefined)
            throw new Error("The parameter 'type' cannot be null.");
        else
            content_.append("Type", type.toString());
        if (categoryCd === null || categoryCd === undefined)
            throw new Error("The parameter 'categoryCd' cannot be null.");
        else
            content_.append("CategoryCd", categoryCd.toString());
        if (fields === null || fields === undefined)
            throw new Error("The parameter 'fields' cannot be null.");
        else {
            fields.forEach((field, index) => {
                content_.append(`Fields[${index}].fildSql`, (field.fildSql === null || field.fildSql === undefined) ? "" : field.fildSql.toString());
                content_.append(`Fields[${index}].fildRelted`, (field.fildRelted === null || field.fildRelted === undefined) ? "" : field.fildRelted.toString());
                content_.append(`Fields[${index}].fildKind`, (field.fildKind === null || field.fildKind === undefined) ? "" : field.fildKind.toString());
                content_.append(`Fields[${index}].fildTxt`, (field.fildTxt === null || field.fildTxt === undefined) ? "" : field.fildTxt.toString());
                content_.append(`Fields[${index}].instanceGroupId`, (field.instanceGroupId === null || field.instanceGroupId === undefined) ? "" : field.instanceGroupId.toString());
            });
        }
        if (files === null || files === undefined)
            throw new Error("The parameter 'files' cannot be null.");
        else
            files.forEach(item_ => content_.append("files", item_.data, item_.fileName ? item_.fileName : "files"));

        let options_: any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processCreateRequest(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateRequest(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MessageDtoCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MessageDtoCommonResponse>;
        }));
    }

    protected processCreateRequest(response: HttpResponseBase): Observable<MessageDtoCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MessageDtoCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    getCorrInbox(body: ListRequestModel | undefined): Observable<MessageDtoIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/DynamicForm/GetCorrInbox";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetCorrInbox(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCorrInbox(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MessageDtoIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MessageDtoIEnumerableCommonResponse>;
        }));
    }

    protected processGetCorrInbox(response: HttpResponseBase): Observable<MessageDtoIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MessageDtoIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    getCorrOutBox(body: ListRequestModel | undefined): Observable<MessageDtoIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/DynamicForm/GetCorrOutBox";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetCorrOutBox(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCorrOutBox(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MessageDtoIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MessageDtoIEnumerableCommonResponse>;
        }));
    }

    protected processGetCorrOutBox(response: HttpResponseBase): Observable<MessageDtoIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MessageDtoIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    getCorrMyRequest(body: ListRequestModel | undefined): Observable<MessageDtoIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/DynamicForm/GetCorrMyRequest";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetCorrMyRequest(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCorrMyRequest(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MessageDtoIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MessageDtoIEnumerableCommonResponse>;
        }));
    }

    protected processGetCorrMyRequest(response: HttpResponseBase): Observable<MessageDtoIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MessageDtoIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}