// Auto-generated by tools/generate-backendservices-index.js
// Do not edit by hand. This file aggregates controller classes for runtime discovery.

import { AdministrativeCertificateController } from './AdministrativeCertificate/AdministrativeCertificate.service';
import { AttachmentsController } from './Attachments/Attachments.service';
import { DynamicFormController } from './DynamicForm/DynamicForm.service';
import { LandTransportController } from './LandTransport/LandTransport.service';
import { PowerBiController } from './PowerBi/PowerBi.service';
import { PublicationsController } from './Publications/Publications.service';
import { RepliesController } from './Replies/Replies.service';

export const CONTROLLER_CLASSES: any[] = [
  AdministrativeCertificateController,
  AttachmentsController,
  DynamicFormController,
  LandTransportController,
  PowerBiController,
  PublicationsController,
  RepliesController,
];

export { AdministrativeCertificateController };
export { AttachmentsController };
export { DynamicFormController };
export { LandTransportController };
export { PowerBiController };
export { PublicationsController };
export { RepliesController };
