//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { environment } from 'src/environments/environment';
import { FileParameter } from 'src/app/shared/services/BackendServices/dto-shared';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');


@Injectable()
export class LandTransportController {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : environment.LandTransportationApiURL;
    }

    /**
     * @param pageNumber (optional) 
     * @param pageSize (optional) 
     * @return Success
     */
    getTransportationRequestsToPrint(pageNumber: number | undefined, pageSize: number | undefined): Observable<VwLtraTransTraficPrintIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/LandTransport/GetTransportationRequestsToPrint?";
        if (pageNumber === null)
            throw new Error("The parameter 'pageNumber' cannot be null.");
        else if (pageNumber !== undefined)
            url_ += "pageNumber=" + encodeURIComponent("" + pageNumber) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processGetTransportationRequestsToPrint(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTransportationRequestsToPrint(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<VwLtraTransTraficPrintIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<VwLtraTransTraficPrintIEnumerableCommonResponse>;
        }));
    }

    protected processGetTransportationRequestsToPrint(response: HttpResponseBase): Observable<VwLtraTransTraficPrintIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as VwLtraTransTraficPrintIEnumerableCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param barcode (optional) 
     * @param plateNumber (optional) 
     * @return Success
     */
    updateRequestToPrintStatus(barcode: string | undefined, plateNumber: string | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/LandTransport/UpdateRequestToPrintStatus?";
        if (barcode === null)
            throw new Error("The parameter 'barcode' cannot be null.");
        else if (barcode !== undefined)
            url_ += "barcode=" + encodeURIComponent("" + barcode) + "&";
        if (plateNumber === null)
            throw new Error("The parameter 'plateNumber' cannot be null.");
        else if (plateNumber !== undefined)
            url_ += "plateNumber=" + encodeURIComponent("" + plateNumber) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processUpdateRequestToPrintStatus(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateRequestToPrintStatus(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processUpdateRequestToPrintStatus(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
  /**
     * @param barcode (optional) 
     * @param plateNumber (optional) 
     * @return Success
     */
    getLLTR_request(barcode: string | undefined): Observable<VwLtraTransTraficPrintListCommonResponse> {
        let url_ = this.baseUrl + "/api/LandTransport/GetLLTR_request?";
        if (barcode === null)
            throw new Error("The parameter 'barcode' cannot be null.");
        else if (barcode !== undefined)
            url_ += "barcode=" + encodeURIComponent("" + barcode) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetLLTR_request(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetLLTR_request(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<VwLtraTransTraficPrintListCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<VwLtraTransTraficPrintListCommonResponse>;
        }));
    }

    protected processGetLLTR_request(response: HttpResponseBase): Observable<VwLtraTransTraficPrintListCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as VwLtraTransTraficPrintListCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
    /**
     * @param file (optional) 
     * @return Success
     */
    uploadData(file: FileParameter | undefined): Observable<StringCommonResponse> {
        let url_ = this.baseUrl + "/api/LandTransport/UploadData";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (file === null || file === undefined)
            throw new Error("The parameter 'file' cannot be null.");
        else
            content_.append("file", file.data, file.fileName ? file.fileName : "file");

        let options_: any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
            return this.processUploadData(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUploadData(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<StringCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<StringCommonResponse>;
        }));
    }

    protected processUploadData(response: HttpResponseBase): Observable<StringCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                let result200: any = null;
                result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StringCommonResponse;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}
export interface VwLtraTransTraficPrintListCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: VwLtraTransTraficPrint[] | undefined;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}
export interface VwLtraTransTraficPrintCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: VwLtraTransTraficPrint;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}
export interface ByteArrayCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: string | undefined;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}

export interface ErrorDto {
    code: string | undefined;
    message: string | undefined;
}

export enum Priority {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
}

export interface StringCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: string | undefined;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}

export interface TkmendField {
    fildSql: number;
    fildRelted: number;
    fildKind: string | undefined;
    fildTxt: string | undefined;
}

export interface VwLtraTransTraficPrint {
    transId: string | undefined;
    barcode: string | undefined;
    rlttBarcode: string;
    plateNumber: string | undefined;
    transDate: Date | undefined;
    companyName: string;
    plateNumberPrint: string | undefined;
    licenseDuration: number;
    replyLicenseFrom: string | undefined;
    vehicleBrand: string | undefined;
    yearOfManufacture: string | undefined;
    chassisNumber: string | undefined;
    engineNumber: string | undefined;
    modelBody: string | undefined;
    numberOfSeats: string | undefined;
    licensesNum: string;
    trafficUnitId: string | undefined;
    governorateId: string | undefined;
    carActivity: string | undefined;
    isPrint: boolean;
}

export interface VwLtraTransTraficPrintIEnumerableCommonResponse {
    readonly isSuccess: boolean;
    errors: ErrorDto[] | undefined;
    data: VwLtraTransTraficPrint[] | undefined;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages: number;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}