import { environment } from 'src/environments/environment';
import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { StringCommonResponse, ErrorDto, API_BASE_URL, throwException, blobToText, FileParameter } from '../dto-shared';
import { ListRequestModel, MessageDtoIEnumerableCommonResponse, MessageDtoCommonResponse, TkmendField, TkmendFieldIEnumerableCommonResponse, MessageStatus, AdmCertDeptDtoIEnumerableCommonResponse, ReplyCreateRequest, RequestedData, Search, MessageDto, AdmCertDeptDto, SearchKind, Priority, ReplyDto, MessageStockholder, AttchShipment, AttchShipmentDto } from './AdministrativeCertificate.dto';

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
@Injectable({ providedIn: "root" })
export class AdministrativeCertificateController {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : environment.ConnectApiURL;
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    getAllRequests(body: ListRequestModel | undefined): Observable<MessageDtoIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/AdministrativeCertificate/GetAllRequests";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAllRequests(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAllRequests(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MessageDtoIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MessageDtoIEnumerableCommonResponse>;
        }));
    }

    protected processGetAllRequests(response: HttpResponseBase): Observable<MessageDtoIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MessageDtoIEnumerableCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
    /**
     * @param body (optional) 
     * @return Success
     */
    searsh(body: ListRequestModel | undefined): Observable<MessageDtoIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/AdministrativeCertificate/SearshAsync";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSearsh(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSearsh(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MessageDtoIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MessageDtoIEnumerableCommonResponse>;
        }));
    }

    protected processSearsh(response: HttpResponseBase): Observable<MessageDtoIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MessageDtoIEnumerableCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createNewFileds(body: TkmendField[] | undefined): Observable<TkmendFieldIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/AdministrativeCertificate/CreateNewFileds";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateNewFileds(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateNewFileds(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TkmendFieldIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TkmendFieldIEnumerableCommonResponse>;
        }));
    }

    protected processCreateNewFileds(response: HttpResponseBase): Observable<TkmendFieldIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TkmendFieldIEnumerableCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param fields (optional) 
     * @param files (optional) 
     * @return Success
     */
    completeRequest(fields: TkmendField[] | null | undefined, files: FileParameter[] | null | undefined): Observable<MessageDtoCommonResponse> {
        let url_ = this.baseUrl + "/api/AdministrativeCertificate/CompleteRequest";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (fields !== null && fields !== undefined)
            fields.forEach((item_, index_) => {
                Object.keys(item_).forEach((key_) => {
                    const val_ = (item_ as any)[key_];
                    if (val_ !== undefined && val_ !== null) {
                        content_.append("fields[" + index_ + "]." + key_, val_ === null || val_ === undefined ? "" : val_.toString());
                    }
                });
            });
        if (files !== null && files !== undefined)
            files.forEach(item_ => content_.append("files", item_.data, item_.fileName ? item_.fileName : "files") );

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCompleteRequest(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCompleteRequest(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MessageDtoCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MessageDtoCommonResponse>;
        }));
    }

    protected processCompleteRequest(response: HttpResponseBase): Observable<MessageDtoCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MessageDtoCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    editFields(body: TkmendField[] | undefined): Observable<TkmendFieldIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/AdministrativeCertificate/EditFieldsAsync";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processEditFields(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processEditFields(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<TkmendFieldIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<TkmendFieldIEnumerableCommonResponse>;
        }));
    }

    protected processEditFields(response: HttpResponseBase): Observable<TkmendFieldIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TkmendFieldIEnumerableCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param messageId (optional) 
     * @param msgStatus (optional) 
     * @return Success
     */
    updateStatus(messageId: number | undefined, msgStatus: MessageStatus | undefined): Observable<MessageDtoCommonResponse> {
        let url_ = this.baseUrl + "/api/AdministrativeCertificate/UpdateStatus?";
        if (messageId === null)
            throw new Error("The parameter 'messageId' cannot be null.");
        else if (messageId !== undefined)
            url_ += "messageId=" + encodeURIComponent("" + messageId) + "&";
        if (msgStatus === null)
            throw new Error("The parameter 'msgStatus' cannot be null.");
        else if (msgStatus !== undefined)
            url_ += "msgStatus=" + encodeURIComponent("" + msgStatus) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUpdateStatus(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUpdateStatus(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<MessageDtoCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<MessageDtoCommonResponse>;
        }));
    }

    protected processUpdateStatus(response: HttpResponseBase): Observable<MessageDtoCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as MessageDtoCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param areaName (optional) 
     * @return Success
     */
    getAreaDepartments(areaName: string | undefined): Observable<AdmCertDeptDtoIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/AdministrativeCertificate/GetAreaDepartments?";
        if (areaName === null)
            throw new Error("The parameter 'areaName' cannot be null.");
        else if (areaName !== undefined)
            url_ += "areaName=" + encodeURIComponent("" + areaName) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAreaDepartments(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAreaDepartments(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<AdmCertDeptDtoIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<AdmCertDeptDtoIEnumerableCommonResponse>;
        }));
    }

    protected processGetAreaDepartments(response: HttpResponseBase): Observable<AdmCertDeptDtoIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AdmCertDeptDtoIEnumerableCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}