import { environment } from 'src/environments/environment';
import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { FileParameter, ErrorDto, API_BASE_URL, throwException, blobToText } from '../dto-shared';
import { ReplyCreateRequest, ReplyCommonResponse, ReplyDtoIEnumerableCommonResponse, Reply, ReplyDto, AttchShipmentDto } from './Replies.dto';

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming@Injectable({ providedIn: "root" })
export class RepliesController {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : environment.ConnectApiURL;
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createReply(body: ReplyCreateRequest | undefined): Observable<ReplyCommonResponse> {
        let url_ = this.baseUrl + "/api/Replies/CreateReplyAsync";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreateReply(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreateReply(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ReplyCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ReplyCommonResponse>;
        }));
    }

    protected processCreateReply(response: HttpResponseBase): Observable<ReplyCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ReplyCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param message (optional) 
     * @param messageId (optional) 
     * @param nextResponsibleSectorID (optional) 
     * @param files (optional) 
     * @return Success
     */
    replyWithAttchment(message: string | undefined, messageId: number | undefined, nextResponsibleSectorID: string | undefined, files: FileParameter[] | undefined): Observable<ReplyCommonResponse> {
        let url_ = this.baseUrl + "/api/Replies/ReplyWithAttchment";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = new FormData();
        if (message === null || message === undefined)
            throw new Error("The parameter 'message' cannot be null.");
        else
            content_.append("Message", message.toString());
        if (messageId === null || messageId === undefined)
            throw new Error("The parameter 'messageId' cannot be null.");
        else
            content_.append("messageId", messageId.toString());
        if (nextResponsibleSectorID === null || nextResponsibleSectorID === undefined)
            throw new Error("The parameter 'nextResponsibleSectorID' cannot be null.");
        else
            content_.append("NextResponsibleSectorID", nextResponsibleSectorID.toString());
        if (files === null || files === undefined)
            throw new Error("The parameter 'files' cannot be null.");
        else
            files.forEach(item_ => content_.append("files", item_.data, item_.fileName ? item_.fileName : "files") );

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processReplyWithAttchment(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processReplyWithAttchment(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ReplyCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ReplyCommonResponse>;
        }));
    }

    protected processReplyWithAttchment(response: HttpResponseBase): Observable<ReplyCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ReplyCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param messageId (optional) 
     * @return Success
     */
    getMessageReplies(messageId: number | undefined): Observable<ReplyDtoIEnumerableCommonResponse> {
        let url_ = this.baseUrl + "/api/Replies/GetMessageRepliesAsync?";
        if (messageId === null)
            throw new Error("The parameter 'messageId' cannot be null.");
        else if (messageId !== undefined)
            url_ += "messageId=" + encodeURIComponent("" + messageId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "text/plain"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetMessageReplies(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetMessageReplies(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ReplyDtoIEnumerableCommonResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ReplyDtoIEnumerableCommonResponse>;
        }));
    }

    protected processGetMessageReplies(response: HttpResponseBase): Observable<ReplyDtoIEnumerableCommonResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ReplyDtoIEnumerableCommonResponse;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}